config/routes.rb
Rails.application.routes.draw do
  get 'page/contato'

  get 'page/sobre'

  get 'page/index'
  resources :lojas
  resources :users

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loja.rb
class Loja < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def tags
    @tags = Loja.find_by_tag(params[_tag])
  end

end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: [:show, :edit, :update, :destroy]

  # GET /lojas
  # GET /lojas.json
  def index
    @lojas = Loja.all.page params[:page]
  end

  # GET /lojas/1
  # GET /lojas/1.json
  def show
  end

  # GET /lojas/new
  def new
    @loja = Loja.new
  end

  # GET /lojas/1/edit
  def edit
  end

  # POST /lojas
  # POST /lojas.json
  def create
    @loja = Loja.new(loja_params)

    respond_to do |format|
      if @loja.save
        format.html { redirect_to @loja, notice: 'Loja was successfully created.' }
        format.json { render :show, status: :created, location: @loja }
      else
        format.html { render :new }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lojas/1
  # PATCH/PUT /lojas/1.json
  def update
    respond_to do |format|
      if @loja.update(loja_params)
        format.html { redirect_to @loja, notice: 'Loja was successfully updated.' }
        format.json { render :show, status: :ok, location: @loja }
      else
        format.html { render :edit }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lojas/1
  # DELETE /lojas/1.json
  def destroy
    @loja.destroy
    respond_to do |format|
      format.html { redirect_to lojas_url, notice: 'Loja was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loja
      @loja = Loja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loja_params
      params.require(:loja).permit(:name, :descrcao, :tag, :segmente)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
      @lojas = Loja.all.page params[:page]
      @users = User.all.page params[:page]
end
  def sobre
  end

  def contato
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    
    @users = User.all.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sualoja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lojas/_form.html.erb
<%= form_with(model: loja, local: true) do |form| %>
  <% if loja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loja.errors.count, "error") %> prohibited this loja from being saved:</h2>

      <ul>
      <% loja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :loja_name %>
  </div>

  <div class="field">
    <%= form.label :descrcao %>
    <%= form.text_area :descrcao, id: :loja_descrcao %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag, id: :loja_tag %>
  </div>

  <div class="field">
    <%= form.label :segmente %>
    <%= form.text_field :segmente, id: :loja_segmente %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lojas/_tt.html.erb
<!-- Modal Trigger -->
 <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

 <!-- Modal Structure -->
 <div id="modal1" class="modal modal-fixed-footer">
   <div class="modal-content">
     <h4>Modal Header</h4>
     <p>A bunch of text</p>
   </div>
   <div class="modal-footer">
     <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
   </div>
 </div>

app/views/lojas/edit.html.erb
<%= render 'page/user_navbar' %>


<div class="row ri">
  <div class="col l4 offset-l4 s12">
    <h4>Nova Loja</h4>
<%= render 'form', loja: @loja %>
<%= link_to 'Back', loja_path %>
</div>
</div>
<%= render 'page/user_footer' %>

app/views/lojas/index.html.erb
<%= render 'page/user_navbar' %>

<div class="row ri">
  <div class="col l8 offset-l2 s10">
    <div class="center">
     <h3>Lojas</h3>


    <a class="waves-effect  btn modal-trigger orange darken-4" href="lojas/new">Nova Loja</a>
  </div>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descrcao</th>
      <th>Tag</th>
      <th>Segmente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lojas.each do |loja| %>
      <tr>
        <td><%= loja.name %></td>
        <td><%= loja.descrcao %></td>
        <td><%= loja.tag %></td>s
        <td> <%= link_to 'Visualizar', loja, class: 'class=" btn modal-trigger"' %></td>
        <td> <%= link_to 'Editar', edit_loja_path(loja), class: 'class="waves-effect  btn modal-trigger  amber darken-2' %></td>
        <td> <%= link_to 'Excluir',loja, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'class="waves-effect  btn modal-trigger red darken-3"' %></td>
      </tr
    <% end %>

  </tbody>
</table>

<br>

</div>

</div>


<div class="center">
  <%= paginate @lojas %>
</div>
<%= render 'page/user_footer' %>

app/views/lojas/new.html.erb
<%= render 'page/user_navbar' %>

<div class="row ri">
  <div class="col l4 offset-l4 s12">
  <h1>New Loja</h1>
<%= render 'form', loja: @loja %>
<%= link_to 'Back', lojas_path %>
</div>
</div>
<%= render 'page/user_footer' %>

app/views/lojas/show.html.erb
<%= render 'page/user_navbar' %>


<div class="row ri">
  <div class="col l4 offset-l4 s12">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @loja.name %>
</p>

<p>
  <strong>Descrcao:</strong>
  <%= @loja.descrcao %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @loja.tag %>
</p>

<p>
  <strong>Segmente:</strong>
  <%= @loja.segmente %>
</p>

<%= link_to 'Edit', edit_loja_path(@loja) %> |
<%= link_to 'Back', lojas_path %>

</div>
</div>

<%= render 'page/user_footer' %>

app/views/page/_user_footer.html.erb
<footer class="page-footer  orange darken-3">

  <div class="footer-copyright">
    <div class="container center">
    Copyright © <a class="black-text text-lighten"  href="/">Sua Loja</a>
    </div>
  </div>

</footer>

app/views/page/_user_navbar.html.erb
<div>
  <ul id="dropdown1" class="dropdown-content ">
    <li><%= link_to 'Usuários', users_path %></li>
    <li><%= link_to 'Loja', lojas_path %></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>

    <div class="nav-wrapper amber ">

        <!-- <li class="brand-logo responsive-img"> <%= link_to 'Logo', page_index_path %> <img class="responsive-img" src="8.png"></li> -->
        <li class="brand-logo responsive-img"> ><img src="/assets/8B.png"><img class="responsive-img" src="#"></li>

      <ul class="right hide-on-med-and-down">


        <li><%= link_to 'Usuários', users_path %></li>
        <li><%= link_to 'Lojas', lojas_path %></li>
        <li><%= link_to 'Sobre', page_sobre_path %></li>
      </ul>


    </div>

  </nav>


<!-- <a href="#index" class="brand-logo"><%= image_tag("8.png") %></a> -->
</div>

app/views/page/center/_user_center.html.erb
        <% @lojas.each do |loja| %>
          <tr>
            <div class="row ">
                <div class="col s12 m12">
                  <div class="card blue-grey darken-1">

                  <div class="card-content white-text">
                    <span class="card-title"><%= loja.name %></span>
                    <p><%= loja.descrcao %></p>
                  </div>
                  <div class="card-action">
                    <a class="waves-effect waves-light btn modal-trigger" href="#">Sobre</a>
                    <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
                    <a class="waves-effect waves-light btn modal-trigger" href="#">Página</a>
                  </div>
                </div>
              </div>
            </div>
          </tr>
          <!-- Modal Structure -->
          <div id="modal1" class="modal modal-fixed-footer">
            <div class="modal-content">
              <span class="card-title"><%= loja.name %></span>
              <p><%= loja.descrcao %></p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
            </div>
          </div>
        <% end %>

        <%= paginate @lojas %>
</div>

app/views/page/contato.html.erb
<h1>Page#contato</h1>
<p>Find me in app/views/page/contato.html.erb</p>

app/views/page/index.html.erb
<!-- naverbar -->
<%= render 'page/user_navbar' %>

<body>
      <div>
        <div class="row">
        <!-- left -->
          <%= render 'page/left/user_left' %>

        <div class="col s7">
          <!-- center -->

          <%= render 'page/center/user_center' %>


        <div class="col s3">
          <!-- right -->
          <%= render 'page/right/user_right' %>

        </div>
      </div>
      </div>
    </body>

<!-- footer -->
<%= render 'page/user_footer' %>

app/views/page/left/_user_left.html.erb
<br><br>
        <div class="col s2 collection with-header"">
          <div class="collection">

            <a href="#!" class="collection-item"><span class="badge">1</span>Saúde</a>
             <a href="#!" class="collection-item"><span class="badge">4</span>Comercio</a>
             <a href="#!" class="collection-item"><span class="badge">3</span>Serviços</a>

          </div>
        </div>

app/views/page/right/_user_right.html.erb
  <% @lojas.each do |loja| %>

<div class="col s12 m12">
  <div class="card blue-grey darken-6">
    <div class="card-content white-text">
      <span class="card-title"><h><%= loja.name %></h7></span>
      <p><%= loja.descrcao %></p>
    </div>
  <div class="card-action">
    <a href="#">Sobre</a>
    <a href="#">Site</a>
  </div>
</div>
</div>
  <% end %>

app/views/page/sobre.html.erb
<%= render 'page/user_navbar' %>

<p></p>
<footer class="page-footer ">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="card-panel light-blue lighten-1 center flow-text">Sobre Nossa Loja</h5>
            <p class="card-panel light-blue lighten-1 center">Sua Loja é uma startup que visa facilitar a divulgação de produtos e serviços das empresas, proporcionando uma plataforma pronta para você. Por meio dela que você poderá divulgar seus negócio, incluir produtos, administrar estoques, preços e promoções, , cada loja virtual conterá outras propagandas atreladas à página que não concorrem entre si. O propósito desta abordagem é criar um esquema de divulgação que facilite a integração entre empresas e o acesso dos clientes aos produtos e serviços disponibilizados.</p>
          </div>
            <div class="col l6 s12">
          <h5 class=" card-panel light-blue lighten-1 center flow-text ">Solução proposta</h5>
          <p class="card-panel light-blue lighten-1 center" >Sua Loja é uma startup que visa facilitar a divulgação de produtos e serviços das empresas, proporcionando uma plataforma pronta para você. Por meio dela que você poderá divulgar seus negócio, incluir produtos, administrar estoques, preços e promoções, , cada loja virtual conterá outras propagandas atreladas à página que não concorrem entre si. O propósito desta abordagem é criar um esquema de divulgação que facilite a integração entre empresas e o acesso dos clientes aos produtos e serviços disponibilizados.</p>

        </div>
        </div>

        </div>
      </div>

    </footer>

<%= render 'page/user_footer' %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="col s12"id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col s12" "field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'page/user_navbar' %>
<h1>Editing User</h1>


<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<%= render 'page/user_footer' %>

app/views/users/index.html.erb
<%= render 'page/user_navbar' %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>
<div class="center">
  <%= paginate @users %>
</div>

<%= render 'page/user_footer' %>

app/views/users/new.html.erb
<%= render 'page/user_navbar' %>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
<%= render 'page/user_footer' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>